modLoader = "javafml"
loaderVersion = "[40,)"
logoFile = "icon.png"
authors = ["Vswe", "Lorddusk", "Newcastlegeek", "Way2muchnoise", "McJty", "canitzp", "ArclightTW", "shedaniel", "kirderf1", "CodexAdrian"]
license = "GNU-3.0"
[[mods]]
modId = "hardcorequesting"
version = "${version}"
displayName = "Hardcore Questing Mode"
description = '''
This mod will add Hardcore mode with extra lives. If you use up your lives, your world will be deleted or you will be banned.
'''

[[dependencies.hardcorequesting]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hardcorequesting]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hardcorequesting]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "NONE"
side = "BOTH"