org.gradle.jvmargs=-Xmx4G

mod_version=5.18.0
maven_group=me.shedaniel
archives_base_name=HQM

# Libraries
# https://mvnrepository.com/artifact/org.jetbrains/annotations
annotations_version=24.1.0
# https://modrinth.com/mod/architectury-api/versions
architectury_version=12.1.4
# https://mvnrepository.com/artifact/blue.endless/jankson
jankson_version=1.2.3
minecraft_version=1.20.6

# Fabric
# https://modrinth.com/mod/fabric-api/versions
fabric_api_version=0.100.8+1.20.6
# https://github.com/FabricMC/fabric-loader/releases
fabric_loader_version=0.16.5
# https://www.curseforge.com/minecraft/mc-mods/reborncore/files/all
fabric_reborncore_version=1.20:5.10.4
# https://www.curseforge.com/minecraft/mc-mods/techreborn/files/all
fabric_techreborn_version=1.20:5.10.4
# https://modrinth.com/mod/rei/versions
fabric_roughlyenoughitems=15.0.775
# https://modrinth.com/mod/cardinal-components-api/versions
fabric_cardinal_components=6.0.0

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=20.6.121
