# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "1.18" ]
  pull_request:
    branches: [ "1.18" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
#    - name: Cache Gradle packages
#      uses: actions/cache@v2
#      with:
#        path: ~/.gradle/caches
#        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
#        restore-keys: ${{ runner.os }}-gradle
    - name: Build with Gradle
      timeout-minutes: 10
      run: ./gradlew build --stacktrace
